openapi: 3.0.1
info:
  title: Employee wage sum
  description: 'Wage sum - demo application with GO language'
  contact:
    email: lsmhun@github
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://wagesum.org/v1
tags:
- name: emp
  description: Everything about employee
  externalDocs:
    description: Find out more
    url: http://swagger.io
paths:
   /emp/{empId}:
    get:
      tags:
      - emp
      summary: Find employee by ID
      description: Returns a single employee
      operationId: getEmpById
      parameters:
      - name: empId
        in: path
        description: ID of emp to return
        required: true
        schema:
          type: integer
          format: int32
      responses:
        200:
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Emp'
            application/json:
              schema:
                $ref: '#/components/schemas/Emp'
        400:
          description: Invalid ID supplied
          content: {}
        404:
          description: Employee not found
          content: {}
      security:
      - api_key: []
components:
  schemas:
    Emp:
      type: object
      properties:
        id:
          type: integer
          format: int32
        empId:
          type: integer
          format: int32
        firstName:
          type: string
        lastName:
          type: string
        mgrId:
          type: integer
          format: int32
        shipDate:
          type: string
          format: date-time
        status:
          type: string
          description: Employee Status
          enum:
          - active
          - inactive
          - deleted
      xml:
        name: Emp
  securitySchemes:
    empstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://empstore.swagger.io/oauth/dialog
          scopes:
            write:emps: modify emps in your account
            read:emps: read your emps
    api_key:
      type: apiKey
      name: api_key
      in: header